# Generated by Django 6.0.7 on 2026-08-24 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyectos', '0002_tarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='Proyecto',
            new_name='proyecto',
        ),
    ]
