# Generated by Django 6.0.7 on 2026-08-31 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_proyectos', '0003_rename_proyecto_tarea_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(default='img/logo.png', upload_to='img/'),
        ),
    ]
